services:
  api:
    build: ./services/backend
    ports:
      - '5000:5000'
    env_file:
      - ./services/backend/.env
  web:
    build: ./apps/frontend
    ports:
      - '3000:3000'
    depends_on:
      - api